class AddMostFieldsToDeals < ActiveRecord::Migration[5.0]
  def change
    add_column :deals, :merchandising_status, :string
    add_column :deals, :turn_over_condition, :string
    add_column :deals, :lease_execution, :string
    add_column :deals, :welcome_package, :string
    add_column :deals, :base_building_cds, :string
    add_column :deals, :kick_off_call, :string
    add_column :deals, :landlord_work_sent, :string
    add_column :deals, :signage_received, :string
    add_column :deals, :signage_sent, :string
    add_column :deals, :signage_notes, :text
    add_column :deals, :permit_submitted, :string
    add_column :deals, :permit_received, :string
    add_column :deals, :permit_notes, :text
    add_column :deals, :check_in, :string
    add_column :deals, :premises_acceptance, :string
    add_column :deals, :construction_start, :string
    add_column :deals, :lay_out_rough_in, :string
    add_column :deals, :fit_out_finishes, :string
    add_column :deals, :fixtures, :string
    add_column :deals, :final_inspections, :string
    add_column :deals, :merchandising, :string
    add_column :deals, :open_for_business, :string
    add_column :deals, :punchlist_request, :string
    add_column :deals, :punchlist_inspection, :string
    add_column :deals, :punchlist_complete, :string
    add_column :deals, :certificate_of_occupancy, :string
    add_column :deals, :as_builts_received, :string
    add_column :deals, :final_plans_received, :string
    add_column :deals, :final_plans_reviewed, :string
    add_column :deals, :final_plans_notes, :text
    add_column :deals, :cad_release_form, :string
    add_column :deals, :close_out_letter, :string
    add_column :deals, :final_lien_waver, :string
    add_column :deals, :construction_cost_summary, :string
    add_column :deals, :sprinkler_shop_drawings, :string
    add_column :deals, :sprinkler_work_order, :string
    add_column :deals, :sprinkler_check, :string
    add_column :deals, :air_balance_report, :string
    add_column :deals, :deposit_release_approved, :string
    add_column :deals, :deposit_released, :string
    add_column :deals, :ta_ti_release_approved, :string
    add_column :deals, :ta_ti_released, :string
    add_column :deals, :final_construction_cost, :float
    add_column :deals, :certificate_of_insurance, :string
    add_column :deals, :w9, :string
    add_column :deals, :utility_cost, :float
    add_column :deals, :tenant_cost, :float
    add_column :deals, :close_out_notes, :text
    add_column :deals, :final_plans_status, :string
    add_column :deals, :signage_status, :string
    add_column :deals, :signage_reviewed, :string
    add_column :deals, :storefront_plans_received, :string
    add_column :deals, :storefront_plans_reviewed, :string
    add_column :deals, :storefront_plans_status, :string
    add_column :deals, :storefront_notes, :text
    add_column :deals, :expiration, :string
    add_column :deals, :date_of_possession, :string
    add_column :deals, :fit_out_duration, :string
    add_column :deals, :abatement, :text
    add_column :deals, :taxes, :float
    add_column :deals, :base_rent, :float
    add_column :deals, :total_base_rent, :float
    add_column :deals, :percentage_of_rent, :float
    add_column :deals, :ti_allowance, :float
    add_column :deals, :ti_cost, :float
    add_column :deals, :ll_work, :float
    add_column :deals, :ll_work_cost, :float
    add_column :deals, :cam, :float
    add_column :deals, :cam_cost, :float
    add_column :deals, :comm_inside, :float
    add_column :deals, :comm_outside, :float
    add_column :deals, :taxes_cost, :float
    add_column :deals, :insurance, :float
    add_column :deals, :insurance_cost, :float
    add_column :deals, :marketing, :float
    add_column :deals, :marketing_cost, :float
    add_column :deals, :trash, :float
    add_column :deals, :trash_cost, :float
    add_column :deals, :other, :float
    add_column :deals, :other_cost, :float
    add_column :deals, :break_point, :float
    add_column :deals, :fee_sqft_total, :float
    add_column :deals, :fee_cost_total, :float
    add_column :deals, :go_marketing, :float
    add_column :deals, :go_marketing_cost, :float
    add_column :deals, :fit_out, :float
    add_column :deals, :fit_out_cost, :float
    add_column :deals, :status_notes, :text
    add_column :deals, :leasing_manager, :string
    add_column :deals, :budget_rate, :float
    add_column :deals, :fit_out_duration_if, :string
    add_column :deals, :budget_ti, :float
    add_column :deals, :base_building_cost, :float
    add_column :deals, :cash_on_cash, :float
    add_column :deals, :budget_variance, :float
    add_column :deals, :increase, :float
    add_column :deals, :action_required, :string
    add_column :deals, :owner_approval, :boolean
    add_column :deals, :priority, :boolean
    add_column :deals, :term_notes, :text
    add_column :deals, :tenant_documents, :string
    add_column :deals, :landlord_work, :string
    add_column :deals, :archive, :boolean
    add_column :deals, :tenant_description, :text
    add_column :deals, :key_contacts, :text
    add_column :deals, :architect, :text
    add_column :deals, :general_contractor, :text
    add_column :deals, :other_contacts, :text
    add_column :deals, :tenant_contact, :text
  end
end
